language: scala
scala:
  - 2.10.6
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_5cd1f76c4e65_key -iv $encrypted_5cd1f76c4e65_iv -in secring.gpg.enc -out secring.gpg -d
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt compile publishSigned