language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_5cd1f76c4e65_key -iv $encrypted_5cd1f76c4e65_iv
  -in secring.gpg.enc -out secring.gpg -d
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.2.3 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
script:
- sbt orgScriptCI
after_success:
- sbt orgAfterCISuccess
