language: scala
scala:
  - 2.10.6
jdk:
  - oraclejdk8
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/decrypt-keys.sh; fi
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt ++$TRAVIS_SCALA_VERSION orgCreateContributorsFile;
    sbt ++$TRAVIS_SCALA_VERSION orgCreateFiles;
    bash scripts/commit-changes.sh;
    sbt ++$TRAVIS_SCALA_VERSION publishSigned;
  fi