language: scala
scala:
  - 2.10.6
jdk:
  - oraclejdk8
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/decrypt-keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.2.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
  - sbt ++$TRAVIS_SCALA_VERSION 'docs/tut'
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/publish-microsite.sh; fi